# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "~> 3.1"

gem "jbuilder", "~> 2.11"
gem "lograge", "~> 0.12"
gem "mysql2", "~> 0.5"
gem "puma", "~> 5.0"
gem "rack-cors", "~> 1.1"
gem "rails", "~> 7.0"
gem "redis", "~> 4.0"

group :development, :test do
  gem "bundler-audit"
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "guard-rspec"
  gem "rspec-its"
  gem "rspec-json_matchers"
  gem "rspec_junit_formatter"
  gem "rspec-rails"
  gem "rubocop-rails"
  gem "rubocop-rspec"
  gem "shoulda-matchers"
  gem "simplecov"
end
